/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/k85RXq1UCw3
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import {
  Carousel,
  CarouselContent,
  CarouselItem,
  CarouselPrevious,
  CarouselNext,
} from "@/components/ui/carousel";

export function Slider() {
  return (
    <div className="mt-[160px] w-[1500px]  mx-auto">
      <Carousel>
        <CarouselContent>
          <CarouselItem>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div className="grid gap-2">
                <h3 className="text-2xl font-bold">Slide 1 Title</h3>
                <p className="text-muted-foreground">
                  This is the description for the first slide. It provides a
                  brief overview of the content.
                </p>
              </div>
              <img
                src="/images/rooms/roomBonbon.jpg"
                alt="Slide 1"
                width={1200}
                height={675}
                className="aspect-video object-cover rounded-md"
              />
            </div>
          </CarouselItem>
          <CarouselItem>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div className="grid gap-2">
                <h3 className="text-2xl font-bold">Slide 1 Title</h3>
                <p className="text-muted-foreground">
                  This is the description for the first slide. It provides a
                  brief overview of the content.
                </p>
              </div>
              <img
                src="/images/rooms/roomPorcini.jpg"
                alt="Slide 1"
                width={1200}
                height={675}
                className="aspect-video object-cover rounded-md"
              />
            </div>
          </CarouselItem>
          <CarouselItem>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div className="grid gap-2">
                <h3 className="text-2xl font-bold">Slide 1 Title</h3>
                <p className="text-muted-foreground">
                  This is the description for the first slide. It provides a
                  brief overview of the content.
                </p>
              </div>
              <img
                src="/images/rooms/roomMocha.jpg"
                alt="Slide 1"
                width={1200}
                height={675}
                className="aspect-video object-cover rounded-md"
              />
            </div>
          </CarouselItem>
        </CarouselContent>
        <CarouselPrevious />
        <CarouselNext />
      </Carousel>
    </div>
  );
}
