/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/laDDwtE2Dyf
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import {
  Carousel,
  CarouselContent,
  CarouselItem,
} from "@/components/ui/carousel";

export function Slider() {
  return (
    <div className="mt-[160px] w-[100%]  mx-auto py-12 px-4 md:px-6">
      <Carousel className="rounded-lg overflow-hidden">
        <CarouselContent>
          <CarouselItem>
            <div className="grid md:grid-cols-2 gap-8 items-center">
              <div className="space-y-4">
                <h2
                  className="text-3xl font-bold tracking-tight"
                  style={{
                    fontFamily: "'Corben', sans-serif",
                    fontWeight: "400",
                  }}
                >
                  Elevate Your Outdoor Adventures
                </h2>
                <p className="text-muted-foreground text-lg leading-relaxed">
                  Discover our premium outdoor gear designed to enhance your
                  hiking, camping, and adventure experiences. Crafted with
                  high-quality materials and innovative features, our collection
                  is your gateway to unforgettable moments in nature.
                </p>
              </div>
              <img
                src="/images/rooms/roomMaple.jpg"
                width={950}
                height={400}
                alt="Outdoor Gear"
                className="rounded-lg object-cover aspect-video"
              />
            </div>
          </CarouselItem>
          <CarouselItem>
            <div className="grid md:grid-cols-2 gap-8 items-center">
              <img
                src="/images/rooms/roomBonbon.jpg"
                width={950}
                height={400}
                alt="Sustainable Fashion"
                className="rounded-lg object-cover aspect-video"
              />
              <div className="space-y-4">
                <h2
                  className="text-3xl font-bold tracking-tight"
                  style={{
                    fontFamily: "'Corben', sans-serif",
                    fontWeight: "400",
                  }}
                >
                  Sustainable Fashion for a Better Future
                </h2>
                <p className="text-muted-foreground text-lg leading-relaxed">
                  Embrace the future of fashion with our eco-conscious
                  collection. Crafted from sustainable materials and designed
                  with a focus on ethical production, our garments are the
                  perfect blend of style and environmental responsibility.
                </p>
              </div>
            </div>
          </CarouselItem>
          <CarouselItem>
            <div className="grid md:grid-cols-2 gap-8 items-center">
              <div className="space-y-4">
                <h2
                  className="text-3xl font-bold tracking-tight"
                  style={{
                    fontFamily: "'Corben', sans-serif",
                    fontWeight: "400",
                  }}
                >
                  Unleash Your Culinary Creativity
                </h2>
                <p className="text-muted-foreground text-lg leading-relaxed">
                  Explore our curated selection of high-quality kitchen tools
                  and appliances, designed to inspire your culinary adventures.
                  From precision cookware to innovative gadgets, our collection
                  empowers you to elevate your home-cooking experience.
                </p>
              </div>
              <img
                src="/images/rooms/roomTruffle.jpg"
                width={950}
                height={400}
                alt="Kitchen Essentials"
                className="rounded-lg object-cover aspect-video"
              />
            </div>
          </CarouselItem>
        </CarouselContent>
      </Carousel>
    </div>
  );
}
